zeus:
  on: false
launcher:
  on: false
  power: 4.0
finder:
  block_filter:
  - diamond_ore
  - emerald_ore
  - gold_ore
  - redstone_ore
  - lapis_ore
  - iron_ore
  - coal_ore
  - nether_quartz_ore
  - glowstone
  - clay
  - sea_lantern
excavate:
  nodrop:
    - stone(0)
    - dirt(0)
    - netherrack
  fortune:
    - coal_ore
    - diamond_ore
    - emerald_ore
    - quartz_ore
    - lapis_ore
    - redstone_ore
light-level:
  on: false
  radius: 8