finder:
  block-whitelist:
    - diamond_ore
    - emerald_ore
    - gold_ore
    - redstone_ore
    - lapis_ore
    - iron_ore
    - coal_ore
    - nether_quartz_ore
    - glowstone
    - clay
    - sea_lantern
  entity-blacklist:
    - bat
    - chicken
    - cod
    - cow
    - horse
    - iron_golem
    - llama
    - pig
    - rabbit
    - salmon
    - squid
    - villager
    - wolf

light-level:
  on: false
  apothem: 8